### ISSUE TITLE
[PE-D][Tester A] Command feedback for `addward`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T12-2/tp#201]
When adding a ward that already exists (duplicated name) with a wrong prefix (`capacity/` instead of `c/`), the error feedback to the user does not convey correct what the issues. Would be better to rephrase the feedback so that the user knows exactly what the issues are (duplicated name and incorrect prefix)

![image.png](https://raw.githubusercontent.com/Beebeeoii/ped/main/files/703bc21a-aef6-4447-9018-7e180b0d4a97.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Beebeeoii/ped#4

**Comment by nramapurath** [comment]
Not counting this as a bug, user should know not to use '/' in ward names
