### ISSUE TITLE
[PE-D][Tester D] Modifying json can cause all the data to be flushed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T12-2/tp#214]
Description: When I modify the medinfo.json file with some invalid value, all the data will be flushed

Problematic behavior: If the user modifies the json directly and accidentally types in a comma or any value that is a invalid for a certain error, all the records in the medical database will be flushed.

Invalid values I have tested include changing two users to have the same NRIC. Modifying ward capacity value to some invalid value. Modifying date to some invalid value. Adding punctuations such as : , . to any part of the file.

For more detail, please refer to the screenshot below.

![Screenshot 2023-03-31 at 2.59.06 PM.png](https://raw.githubusercontent.com/kyueran/ped/main/files/d0f9f158-f623-4e3c-a213-027bca0ca5e1.png)

![Screenshot 2023-03-31 at 3.00.31 PM.png](https://raw.githubusercontent.com/kyueran/ped/main/files/d0c824cc-49ae-49db-9c4e-cbeadaa816ff.png)

![Screenshot 2023-03-31 at 2.46.13 PM.png](https://raw.githubusercontent.com/kyueran/ped/main/files/f579b3cb-a1f4-4b6b-a501-95bd41a984a4.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: kyueran/ped#6

**Comment by nramapurath** [comment]
Consider this a documentation bug, we need to mention in the UG that directly editing the json file carries with it the risk of losing all your information if the file is corrupted
